backend:
  name: bitbucket
  repo: perossing/bhblog

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Post Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", default: ""}
      - {label: "type", name: "type", widget: "hidden", default: "post"}
      - {label: "Post Text", name: "body", widget: "markdown"}
      - {label: "Post Picture", name: "picture", required: false, widget: "image"}
      - {label: "Picture Caption", name: "caption", required: false, widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Category", name: "categories", required: false, widget: "string", default: "uncategorized"}
      - {label: "Tags", name: "tags", required: false, widget: "list", default: []}

  - name: pages
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Page Title (shows up in Main Menu)", name: "title", widget: "string"}
      - {label: "Page Content", name: "body", widget: "markdown"}
      - {label: "type", name: "type", widget: "hidden"}
      - {label: "menu", name: "menu", widget: "hidden", default: "main"}            

  - name: "Settings"
    label: "Site & Home Page Settings"
    files:
      - name: "data"
        label: "Settings"
        file: "data/data.toml"
        extension: "toml"
        fields:
          - {label: "Blog Intro (first paragraph of Home page above previews)", name: "intro", widget: "text"}
          - {label: "Blog Name", name: "title", widget: "string"}
          - {label: "Header Image (at least 1060px wide)", name: "image", widget: "image"}
          - {label: "Posts per Page (Number of previews that show on side menu and 'more posts' pages)", name: preview, widget: "number"}